// flow-typed signature: 8a3298597c0e6ddd60ef7225bab363f8
// flow-typed version: <<STUB>>/ffmpeg-static_v^2.4.0/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ffmpeg-static'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ffmpeg-static' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'ffmpeg-static/index' {
  declare module.exports: $Exports<'ffmpeg-static'>;
}
declare module 'ffmpeg-static/index.js' {
  declare module.exports: $Exports<'ffmpeg-static'>;
}
