// flow-typed signature: e83c26bdbcb004fb2940cab8fc4078ab
// flow-typed version: <<STUB>>/ffprobe-static_v^3.0.0/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ffprobe-static'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ffprobe-static' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ffprobe-static/tests/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ffprobe-static/index' {
  declare module.exports: $Exports<'ffprobe-static'>;
}
declare module 'ffprobe-static/index.js' {
  declare module.exports: $Exports<'ffprobe-static'>;
}
declare module 'ffprobe-static/tests/index.js' {
  declare module.exports: $Exports<'ffprobe-static/tests/index'>;
}
