// flow-typed signature: 6d4802df74534baace0d84a1eb8a3acd
// flow-typed version: <<STUB>>/reset-css_v^4.0.1/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reset-css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'reset-css' {
  declare module.exports: any;
}
